---
name: "Reviewdog"
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  misspell:
    name: "Misspell check"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Check misspell
        uses: reviewdog/action-misspell@v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          locale: "US"
          fail-on-error: true
  yamllint:
    name: "Yamllint check"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Check yamllint
        uses: reviewdog/action-yamllint@v1.4.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail-on-error: true
  deletct-secrets:
    name: "Detect secrets"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Check yamllint
        uses: reviewdog/action-detect-secrets@v0.6.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail-on-error: true
