name: "Terraform test"
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  terragrunt-plan:
    name: TFLint base-infrastructure
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.37.1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.1
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.8.0"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/572194382423/locations/global/workloadIdentityPools/github-auth/providers/github-provider2"
          service_account: "terraform-organization-sa@sebastianneb-seed-2022.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0.6.0"
        with:
          version: "387.0.0"
      - name: Gcloud Checkout
        run: gcloud projects list
